### ISSUE TITLE
Bulk export / query from the API

### ISSUE THREAD

**Issue by mbeilin** [datopian/ckanext-datastore-bigquery#3]
When the user queries the Datastore via API and the result hits the limit (server can return) we want to return a file pointer they can download rather than stream rows.

Response (TODO: check current CKAN response and get as close as possible to basic structure - [CKAN current srtucture](https://github.com/ckan/ckan/pull/4562))

```
{
  "success": "true"
  "records_truncated": "true",
  "gc_urls": [
      {
          "url": path-to-url-0
      },
      {
          "url": path-to-url-1
      },
     ...
  ]
}
```
Est: 4d

## Acceptance

Normal default API response up to e.g. Xk (somewhere between 30-100k rows). above that switches to response that points to output files that you can download.

* [x] Up to Xk normal response
* [x] Above Xk get bulk response

## Tasks

* [x] Research how bigquery does bulk export ...
  * Queries over certain limit export (how do we know result size ...?)
      We can know the result size(num of rows returned) after the first query run.
    
  *  Return the file path ...
     When we know the file size it's posible to consider the number of files and their URI(s) - the max file size is 1G. 
There are three main options for [Exporting data into one or more files](https://cloud.google.com/bigquery/docs/exporting-data) by setting `destinationUris` property:
        1.Single URI
        2.Single wildcard URI
        3.Multiple wildcard URIs
        
  *  Clean out temporary storage ...
     Temporary table that is created to store the query result exists for up to 24 hours. We are not charged for storing temporary tables according to this [doc](https://cloud.google.com/bigquery/docs/writing-results#python).
* [ ] 3 stage process
  * [x] Check query to see size
  * [x] If below threshold do normal
  * [x] Otherwise
    * [x] Execute query and store in temp table
    * [x] Export table to cloud bucket (some directory)
      * [x] Delete table
    * [x] Return response
* [x] Setup some kind of cleaning job to delete old exports

## Analysis

* Exporting data from BigQuery tables: https://cloud.google.com/bigquery/docs/exporting-data
  * Basically we can export(download) up to 1 GB of data to a single file, beyond that we must export the data to [multiple files](https://cloud.google.com/bigquery/docs/exporting-data#exporting_data_into_one_or_more_files).
  * As best practice to read data from BigQuery we should use [Dataflow ](https://cloud.google.com/dataflow/docs)
    * [Google BigQuery I/O connector](https://beam.apache.org/documentation/io/built-in/google-bigquery/)
  * The other way to export data from BigQuery is Submitting an extract job via the API or client libraries: https://cloud.google.com/bigquery/docs/exporting-data#exporting_data_into_one_or_more_files

* Calculating query size, in short `When you run a query, you're charged according to the data processed in the columns you select, even if you set an explicit LIMIT on the results.`
* [how to calculate the size of the query bigquery?](https://stackoverflow.com/questions/37303738/how-to-calculate-the-size-of-the-query-bigquery)
* [Query pricing](https://cloud.google.com/bigquery/pricing#queries)

QUs

* Can you export a query or the whole table? **No, you can only export a table**
  * No, afaict you can only export a table https://googleapis.dev/python/bigquery/latest/generated/google.cloud.bigquery.client.Client.html
  * https://stackoverflow.com/questions/50499049/bigquery-export-query-results-to-local-file-google-storage
  
    > BigQuery does not provide ability to directly export/download query result to GCS or Local File. First you need to get result of query either in explicitly set destination table or if not set you can use temp (anonymous) table that holds query result - you can get it (table) from respective job attribute configuration.query.destinationTable (after job is completed)
Then you can use that table as a source for Export job
* So need a 2 step process: query to a table and then export that table.
